CREATE OR REPLACE TRIGGER EMPLOYEE_BRI 
BEFORE INSERT ON EMPLOYEE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDEMPLOYEE IS NULL THEN
      SELECT EMPLOYEE_SEQ.NEXTVAL INTO :NEW.IDEMPLOYEE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
