CREATE OR REPLACE TRIGGER FAMILYMEMBER_BRI 
BEFORE INSERT ON FAMILYMEMBER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDFAMILYMEMBER IS NULL THEN
      SELECT FAMILYMEMBER_SEQ.NEXTVAL INTO :NEW.IDFAMILYMEMBER FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
